apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  labels:
    app: jellyseerr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /app/config"]
          volumeMounts:
            - name: config
              mountPath: /app/config
      containers:
        - name: jellyseerr
          image: ghcr.io/seerr-team/seerr:v3.2.0
          ports:
            - containerPort: 5055
              name: http
          env:
            - name: TZ
              value: America/Chicago
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyseerr-config
