---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wg-easy-admin
  namespace: wg-easy
spec:
  encryptedData:
    password-hash: AgB/qUOyL9CplGzdNv4JsECBhEc8wPNHnrw0DAkFXrsObfvduk5FoGHVGD7Q7kG8MmD54hLXGK9aW/X7siQYFpoAZiqDZdjOp0AUe/HVPp49A1fU4IOJrpAiUmvj4R0juYuez33KUz0JcYDhBzE1Sn46cLdmF23wrz+p9bnV7xLdBpeYn2BGcBhdJA6EMUBuY88FRSIDUSoBC12yILBcsZ1qwLfZnOpnqQtwK2UtmDHI0To84T7j7XQHVKEgxhE8a/agPk6+GhASX6t8o/zDOXRLwFzpytDoqbCxP+MxU/wyy9X1M/mszsjl93gmMDvfi3FR/RWyt0mmbwnCwoHivlierL2/k+gehry6qAe7T8JB1o3MKQJ6AE1P5UEEvLdKfw6RwztF4sKs45Zq/7zg3au1wXup9lREu3Zs1uQ4HJzC4M8G2PdJq6bcel1lVPg0+dZWafeyo6cYrXrWNQzKvFMHsbWkTsXjEOJBA79+C5u43fvi3YaU1CLCSrycS4Gxqtbn8+8qzRRBjdIuSXNchsLtI5/awgSG/BB8jmFK3nmbNUGiTkqJCGwPZe0zGcCEm0Tohgx6qcIy9BKm+9VHXKqf9REo1445xFdlNJeuSyErn2/dwXQ8h+cvULoixSXcHYg0vsap/h+2/OS0i/Y/oYka5vKM190IYFIgZbGMwVo1suG3oaXLBa5Lrae1oF9kabcwyG5Unwx+uw0ot9Ud1UBbGke3fNWMebCZ6MUcFRgAJe2XKYhwH7KyeQ/MCbihz+lLbJYhCfQc5sI4lyI=
  template:
    metadata:
      name: wg-easy-admin
      namespace: wg-easy
