apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
  labels:
    app: blocky
data:
  config.yml: |
    upstreams:
      groups:
        default:
          - 1.1.1.1
          - 1.0.0.1

    blocking:
      denylists:
        ads:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - |
            /^ad([sxv]?[0-9]*|system)[_.-]([^.[:space:]]+\.){1,}|[_.-]ad([sxv]?[0-9]*|system)[_.-]/
          - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/domains/pro.txt
        security:
          - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/domains/tif.txt
      clientGroupsBlock:
        default:
          - ads
          - security

    customDNS:
      customTTL: 1h
      filterUnmappedTypes: true
      mapping:
        home.drewdevlab.com: 10.0.4.240
        grafana.home.drewdevlab.com: 10.0.4.240
        argocd.home.drewdevlab.com: 10.0.4.240
        n8n.home.drewdevlab.com: 10.0.4.240
        wg.home.drewdevlab.com: 10.0.4.240
        prowlarr.home.drewdevlab.com: 10.0.4.240
        radarr.home.drewdevlab.com: 10.0.4.240
        sonarr.home.drewdevlab.com: 10.0.4.240
        sabnzbd.home.drewdevlab.com: 10.0.4.240

    ports:
      dns: 53
      http: 4000

    prometheus:
      enable: true
      path: /metrics

    log:
      level: info
