apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: crowdsec
spec:
  encryptedData:
    apiKey: AgA51W0YaGcUsutr5o6Fr603bNK+8DH6giGoOZrcj4PlTmZSLgCwXG/BRj7IidvyNgo5yTJ1YP9YKlLvTpPFxnL1TLW2YpTRrXfuSdI4d+10k/o2tqaG5zm14F+wThMdQpxLkY9nUSaOHt6YWtYczzwhSxFDwfnlkZKsVR96zjDYUcv2/Cryz+nCucnulogKzNzgaTjwHSJ6utsQf2rjiZudV4CO9iqL+1nqpsb5fKydi/LtESHLyGRlGNJh0MDUWmvZbwDB3eR8oedzK6IAHHLE7WDlx0Xlel6U1D6qmHiEbqwPzxqabHe1BBVgDE33lV23XVlZ99nNAPyzLft0cNxB7xIqSKQ5Xufkcj+bubD+xXR3SsWZ2r5KNGh67wGL+YQoVb5yy/Bwe6p4G+IKbQXEzZhH8uRzQQHpifXz8lUTmMW6KLl5wpIgo9+d9FrQtpOz/j9dMwEEmD6CgmIEFXTxfL/2h0Tiip6nU9mVJ2u6n5DPLpsUaNTdXDn6PI0Qlz5XP1zl1lpsPyFogI0mOBQpBu8SD3vU5OqhNzGZfOiMSiIIov0We7HXwdOAuu839zCZPtLY82OfbFMZ1yBlF/moFcIPCw3mvhIB9KBlhCqyckRKxLfNR88X+6yDbP4ZpOOy+YRMv/aAsP6TnjpalfwX+kYDEyDeE9hK/4PsC2vOd73PI1Gnpc0V2L4+IUb2TE3S1G5j6MKLdeG35HazJUpt+nPHOX3f0SP4Z16AsrZaVcvTXxkybOnbONYz
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: crowdsec
