apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: crowdsec
spec:
  encryptedData:
    apiKey: AgBJGLMOalrRe7GVy9nBTXIdRk3/7aNc6VAx6roDFesk4jr/v6Tf2bpdhUJd6Nbsg1Yc7G/VBw6P0OVoOMxgVIrP9HBkgPQI9IwwvqYwDY0Y5ln4BfO5oKBCbf3JSDp0e6+AdD/q/xckoByL5d9fRI+cs8hywdXPf7+fQnvPEKpQPWxJ8VDJlcIL0UHonFh22h+ppszmu09F1WPaWyvQPfKIxD862TFABj78hqovFip4c7cracooc9r55Uu45imGRK6LfYu0YA9rCPKvQItOH6BVB84OFSJjGMdR2Hl81X0PVCtaSIaCLbfBL5vWj9vHSVCDD7mcwWnsvk1eMjjRxVDu35i8M10CI8WMlFU9fbKa04AItnV5wA4yon2tCm2K0g47/dypTQ1cQNDIyzsZU3nZQwFub9GdQHinVd1iEbiKLFW3y9KNsY7/UqOQAN/8Ci78svjg6NvFP53p6U+dhpZ1jTzOmzl/NRg+VzqfRRvrakBLzIH0z+kmB43jRMN/OZffhSUUUdWyyQ5evwxPiuwLTdYv7Gqx+ABVcqiA2U8NHJFOI7MheP9UoJRrqbnWFWvN5kb91x2o/RaPluuq+5uBrTnIBK23dgAbZAwgdbnNbJZZ+C7qF8ITC8YhMNriM0PQs/CaChoreCziwRKCJzmJf8H7SuKaYAGYfKaD+qeZoe0ozyyFIYEw3rVb59MNCXJiKDS2dGQ0q6sRH6ct3Ph1khYUzyH3JsdEbhC688A0x+/qisJvTjxrMOrt
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: crowdsec
