apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-media
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=4.1
  csi:
    driver: csi.san.synology.com
    volumeHandle: bazarr-media-static
    volumeAttributes:
      protocol: nfs
      dsm: "10.0.4.42"
      source: //10.0.4.42/k8s-csi-pvc-15af394e-b14a-4a35-9
      baseDir: /volume1/k8s-csi-pvc-15af394e-b14a-4a35-9
