apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: bazarr-media
  resources:
    requests:
      storage: 10Ti
