traefik:
  api:
    dashboard: true
    insecure: true

  ports:
    traefik:
      expose:
        default: false

  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: "10.0.4.240"

  ports:
    web:
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
    websecure:
      http:
        tls:
          enabled: true
