traefik:
  api:
    dashboard: true
    insecure: true

  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: "10.0.4.240"
    spec:
      externalTrafficPolicy: Local

  experimental:
    plugins:
      crowdsec-bouncer:
        moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
        version: "v1.5.1"

  ports:
    traefik:
      expose:
        default: false
    web:
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
    websecure:
      http:
        tls:
          enabled: true
