apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: sabnzbd-storage
  resources:
    requests:
      storage: 10Ti
