---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sabnzbd-vpn
  namespace: sabnzbd
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgBTzmabCvOntlGNM2e/2LeP+0sSNs8JEWWNeEOmaRiGR45TnuQwVwxrMvtEOLGYrXRxkIcGOY9J3caQ4x0+8YJjElNzl45ZmTMHb6GxBhFhWnBJlbfQAdEp1sozqoA5TigvG0rjyQvRSinOccTeYVQoo7L/rXIJxBTnHvPn1jhQAqkrrY2dFlFNJYdDpvPXCX4VFzFXd6c9Knk7LEWbOwx3zD2Y1Z3Lo762y1BlnnEhKN680xnBdXdPmBYHpC2S00qhbDIBEeAn3g5my9MruYcLfQfCUxTxR98xw0onnP/ItaHCWpLaAJh0f5Ng1oaCuivsVIdPyYfUtqiBojFSFkN2VEgQ/VZ1ZhvnYVw2m6nsmzyXjeGba+vlsIQAitMELSFv4ozqd/NEuG+jmlsKz1YytLHlkfqzXxrtvX/9KklvUGQcU3G5d/Cj8CK5SIvYov2iFltAYUHyr00tX8hn25i5Cp3acB+LasPX++LmA17gvQUj31QAWgJAE86bXTWItwqtKViQ38w49erqs+zDMP/o6eEi0f6wQpM7ztVeXDEL0Njhv5lROnBKp1Q7Lzk9NzU5pUfnc9WSqX9Dy+wAwZMqLOyJ3CJLgv982XnQXQXBk7oVwI/n3O97RFeAoiKueSVPALJpQbj74ys2fS6Z/pzf/oQ/LmzQhHQ+XqYJkeYBjXiJ0SfbTBsYPOA+iDBqKjAliulowgzJzB2a/Odmggt9zHwTdpdGZKvublWwSX34U/05puSY9CqICEQ1rg==
  template:
    metadata:
      name: sabnzbd-vpn
      namespace: sabnzbd
