---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sabnzbd-vpn
  namespace: sabnzbd
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgAAOd4S59MatTaLhNSjGYoE143NSIxFOCwKPztb3ejv1mh48CAQ6BFvENcTQlVPEFF1g8XzywTYLNttpFpc3rJ/UF+yPc1E+uI1neY5vuieY7kX+ag+AAVZUpCFC8MC/hXt6pydn58yjhdaB85CoE0mOsQ/+PvreKixeRyH1LzkGIzmq6sZD9/7A9iTMXRtKlhZ2XgtA22kODTYtS7f01WgxeX3T5YEjSVeWRaXmUxGedbEkHYsj9CcZyKC+fFM1XWZsBHdBagyD7A/+gsAqZHji4PchL6sfgZU1x2GHDR4PR7D0t3kYNbUX8PtcvHnfDLhu3yK2hRmFaWoBlFhOdh/hubAmm4mS9RafGAt5blktYOB3Ng5LB+/Gjj5A4l5w4PwJYI8qgw/UrXDkzm74AsBdBMyXpXMIhTUgaMEM0achTeZMte0ZYsfOxtWMDk5bK3EKM+v4I4hx8LvQ7lBMTzg0/rEZoD62+HHpbZ9+HxrfZQobCjBg9HKjLj+qwi9c1HKiz6J4MXlnVJ5m8UR3Z1Hd8wv7KaALT5StWfmfm7dcz1aJ8ecmvwAKvOb6fgsu1YvzP7De4cWPdmUQwXXiIABxxj+RZ6iXLSqSdh7aeh59LR+bKZO68krYFfLEnyxcCeDa+eQhC8qXqpvnnAEWsoEp7BfGIFxqT6lI3sg/0mVTQC0p/Kqs2VDYWJ/PTbnN5+xFfBe8N42w3NIhRMrk0/OafNBAcz3ZpWBM0OhFvc2MjL4JMOke4YiMVCbpg==
  template:
    metadata:
      name: sabnzbd-vpn
      namespace: sabnzbd
