---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sabnzbd-vpn
  namespace: sabnzbd
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgAsnv8fW4FEkv3rlfaf5NDTR4N7PrjkG5U3sBk66hIyKMiNh0oLPrblumD4xzKNo298bhSuEMGlxwrN9TNXg1ktQyvfFawPRntuOrAgvFyCcJhAsR2YVQVoqI+VB1tVy/0RUu6mWhtL+5SPW8AnoyVeLN4UFc4c01Co1gYXMnnQjIJGDrDBQpTdsklmIb9jm46wl5vonE3OTF280bzoWZ6bulrTdl9kl9N0Esirf/0pT67t+hjG+RUhrYQQQajGkosPgZlZ4e8lJgvCN0MZYQDusGS446G0mVrx9gEucPKdQG0hQ34ZhXP8zGVI6kXjesha6PTIKYEHTUhL5xCkDzIxcQDtZ06peMuQJb8krAMXaN6UJmq8FillpaT3+Ru9Ys1JkVBF0+MAkEl0ZZsfA2ywZktzA9nP90i2dXd5/+a33dlLZQZADmzPEc+eRvMPG17n4Rr8NGJwrRRkk6FCtG5Y8wmk5gcc10EvhA2DUI0aCdtRNJkeVr6/t+eOC86P2QuVPiqW2a6SBRIrgbvtM3jp5bPeEFeHkNZ7dBAK0cLrWo6rauX1q1JQvM0c8wwAxTz1f/fEQb5RLpjKu8DTdVnhlPZboC0/bIH4sZHyv5/0sZfeB5/Wv/5bUDnMGJlJvPTEZYs+UnuUIY8qP4tpos+DXgMjCXKQfsySv9p5dFiKF4s6i4DVaSYc+QSC2wCFSrHKxvEJhgGpzeifWHilqZCas4NLqLVpG3uHxwXPv1AeboI2KJxVvrQhsbNLdA==
  template:
    metadata:
      name: sabnzbd-vpn
      namespace: sabnzbd
