apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-downloads
  labels:
    app: sonarr
    type: downloads
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 10.0.4.42
    path: /volume1/k8s-csi-pvc-15af394e-b14a-4a35-9/downloads
