apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: sonarr-downloads
  resources:
    requests:
      storage: 1Ti
