apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db
spec:
  instances: 2
  storage:
    storageClass: longhorn
    size: 5Gi
  bootstrap:
    initdb:
      database: n8n
      owner: n8n
