apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: n8n
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: n8n
  podMetricsEndpoints:
    - port: http
      path: /metrics
