---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB4zeLSgDp+r96npfaZSfhwTBV/MhBWuxz612Zuz3rnEtE4KXbkBEDXrziEoyCSZS09ZEhFFQSK1p1B+ErikmKcatuD8/8sm1QKuvJlxwSpJ1uYv/PDdkdwlWMu9cM//AEWm+BeGjHclC5UjZVULKYjcHiiA8JAC5qsW5S6SfTZdpW+ojkCy99J469ukIVPkIJ2gjQEEZ2SNXVJY/z55KOTrwuPZ9yLy10FYc9Do06lbnqbp4DQbqNPDnRWlFYawv60zhyZXkFI2OVI1YUXueOZ1l38QExj9EfqdpGau7gdEY7j4a737lKaf5wdIcqPf+kgRFPfyzXcasuPZVX8TZXr7eAP1mIuOB2dXbMxL/AkuFE3ZhG64zWbfnsx2UGcOqTSaioztZ89ZdyLV/2GeKt1e0taa8NxDIV5p2Z1BQyagIs+xDxsjXjxYFzXauLQRS9m/ggIaqMdlSpIFJKQPOaWVu7WeSbJMvtFa5ymoD7lPlGRluuO9MlTRPqBLwaKBnGQXm/m5XU05B8VDlM1GSKlyL5xP67vSil8TFKp/HY7f9kIRFTUEicyqDbUhpDFncpmDz5wyYydiIfNCp1yIEolWuVinpjeus8XnsRTy5Fq9VxUAlj6T5s9gz4ZVJ1pvM0KV/qufA0htSX+CZbVCFifYa8TjoL7lWwoD1HuNtkJC5LdjkVYZ73WlMkPnqZ0XY6Qd3APm34u6iuE7uwH1gYGnjZZ/0YmJqaJP/2VW2HqI44iOC0mMFZK5XdqJDYErUihsHps6Q==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
