apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: ssh://drew@10.0.4.37/home/drew/code/homelab
    targetRevision: main
    path: infrastructure/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
