---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: ddclient
spec:
  encryptedData:
    api-token: AgCBDLuJ7lTaA03w5wrg5BRqJMVuiSGMS61qkRylG6H2eFgIsdYDAfz64PugyV9akmb0fLZE0XvTGpEGWyKpai4x3DxiJezdCdQVa0axp/ccD9UrH1kXy8sQPWWbjMdny8z4Q41KnW8rOEYzhO9n+cSdbRt1KVAfUDfxpjNOMM3TEy+LiuMppzeFZZHnEeGfqgCwelvJPuxN6TjWoQui6I8dxEPouNr/33ONlH1X20l1lnKxupiZdX1f7SiX8KWZnOrfPCHqk/jnovsEVEBcRKwSYCTR86AxpE7FKMh/fvy4fmb6HbRiRv0JmXRQnn+31+9XXLAgz/QrcwGHETCBRWbu/1lgISvZsq8DEz1gjaWRiWg9BZCoGskofGLc8FLfKXupoJ8BOjf+YP7bipxM9S0gvVilDi4M1NteTbNcH6A/51SQkZP1gSaymjlB+q91gr3FgRCEXvwt9KWFAi0WBKZ+CizSoiR8kDQsZhkSnAC78Ba9DzsCzz4iAsR+B+5gM87hMqdPOvWgjiFsp45v5E13puJ8c41t7NFzZVe4bqPEe8wYjH88uUhwGy1umGfHZycaknze2yKAe5u/mFHKhaTf35S5PBapDeqIp9VGLz4j5d+OcACHTJ7jv4xFuCXPqulFTOqMSiev8NsOMde7KunBCeR9fGQuG0a4j0/nGRrats0EvyGigqdqh5UqFhI+1Tj/HuHwXuAu076cPrQeyDTlwIGHjbI4JILmqC8ZJMicCE/Eke8eZBRodM+gQdoTW2yM1godVg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: ddclient
