apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bazarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: ssh://drew@10.0.4.37/home/drew/code/homelab
    targetRevision: main
    path: workloads/bazarr
  destination:
    server: https://kubernetes.default.svc
    namespace: bazarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
