crowdsec:
  container_runtime: containerd

  lapi:
    replicas: 1
    persistentVolume:
      data:
        enabled: true
        storageClassName: longhorn
        size: 1Gi
      config:
        enabled: true
        storageClassName: longhorn
        size: 100Mi
    env:
      - name: BOUNCER_KEY_traefik
        value: "<will-be-replaced-with-sealed-secret>"

  agent:
    acquisition:
      - namespace: traefik
        podName: traefik-*
        program: traefik
    env:
      - name: COLLECTIONS
        value: "crowdsecurity/traefik"
      - name: PARSERS
        value: "crowdsecurity/cri-logs"
