---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synology-csi-client-info
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yaml: AgCIuton/kNm+NfBidWi6mYMvo8A2OCAKhXyBWOkVLItb3QDicaJL0a7NpnJT4Zfovz8aTlMXVROzBXHKpxs7M+dNASmKH6jJ9zA5m2G21MRb95g1krLDmFhDGv8HCGthnePtkXcaczN5Kqj4mtNfuFU8YlOqw34wBV4/ud7gVP61e3eRMyoQgFlfyL42L9aWm8dpgMSVTN5BPFw2OaX9Q+HlINo0PskqJ16TFzhi9T0I4Zi4q2kfGAld747rmxJOZgKTGl+aP3cJPJnI2FRMB4EFdHJuDNQGCjkdssSXAkcOwgks4ad62LT/bwxicVrV4shoUQowSkEikylT2i+dGqLJHhv6vV1KEE+5kCI19Ccfaft/5nBEfUuwfkyrOTe2M1S21GIVFGvhwtb9MLnHvwsSq2+QYQazuXNhr9yCV2Q/KC7JwsW0NizyUgXzUA6tQwBOSeTjCHZhuo30qrt+qgbM/xiCPWU6MqEbagZqUenIhkXQjJEYNYoRAybiUry7xjtdknBjZu0C1e2oTswTpyB2FmUXCuS96fksZci9jT4HtLKYr5leNUuYucmAkUuCq2kJrq00mXQCI+2Hk7tgLx1ywIzF7zzHG65K/EsYiE6be2phwikMDjb3Ono/9smVp3Y3nLc6SZyEz/pNP9Lj0j38jemh0nEO13j75w8S/dtGYPxQ9FIimIYyi/9nvj54zbVsyfLXPNdO5VQa4rVkVIZDOLzlHf52FZI+7ekqT+DVXemPijdC37o9FgGgmAZhDCr3LP/F9ugfmMAnUgrgg0GehuTnNo374NFTdauriY6GjTf87r7AJzfbga0MPahf5ePANhsM/hQNbLCiGGt
  template:
    metadata:
      name: synology-csi-client-info
      namespace: synology-csi
