apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
spec:
  entryPoints:
    - websecure-internal
  routes:
    - match: Host(`radarr.home.drewdevlab.com`)
      kind: Rule
      services:
        - name: radarr
          port: 7878
  tls: {}
